Repository matej494/Marsiple, pull requests merged in 2018-07, with the labels that each got.

#1 Added 'MartianColors' enum and colored the app.
  Marsiple.xcodeproj/project.pbxproj
  Marsiple/App/Posts/PostTableViewCell.swift
  Marsiple/App/Posts/PostsView.swift
  Marsiple/App/Posts/PostsViewController.swift
  Marsiple/App/Tab Bar/TabBarController.swift
  Marsiple/Common/Extensions/UIColor-Marsiple.swift
  Marsiple/Common/Network/.gitkeep
  Marsiple/Common/Persistence/.gitkeep
  Marsiple/Common/UI/.gitkeep
  Marsiple/Common/Utilities/.gitkeep
Labels: aproved

#2 Fetching posts
  Marsiple.xcodeproj/project.pbxproj
  Marsiple/App/Posts/PostTableViewCell.swift
  Marsiple/App/Posts/PostsViewController.swift
  Marsiple/Common/Localization/LocalizationKey.swift
  Marsiple/Common/Models/Post.swift
  Marsiple/Common/Network/HTTPRequestHeader.swift
  Marsiple/Common/Network/HTTPRequestMethod.swift
  Marsiple/Common/Network/MartianApi.swift
  Marsiple/Common/Network/PostsFetcher.swift
  Marsiple/Resources/Localization/Localizable.strings
Labels: aproved

#3 Posts
  Marsiple.xcodeproj/project.pbxproj
  Marsiple.xcodeproj/xcuserdata/matejkorman.xcuserdatad/xcschemes/Marsiple.xcscheme
  Marsiple.xcodeproj/xcuserdata/matejkorman.xcuserdatad/xcschemes/xcschememanagement.plist
  Marsiple/App/AppDelegate.swift
  Marsiple/App/Posts/PostTableViewCell.swift
  Marsiple/App/Posts/PostsView.swift
  Marsiple/App/Posts/PostsViewController.swift
  Marsiple/App/Tab Bar/TabBarController.swift
  Marsiple/Common/Extensions/String-Marsiple.swift
  Marsiple/Common/Extensions/UIColor-Marsiple.swift
  Marsiple/Common/Extensions/UIView-Marsiple.swift
  Marsiple/Common/Localization/LocalizationKey.swift
  Marsiple/Common/Models/Post.swift
  Marsiple/Common/Network/.gitkeep
  Marsiple/Common/Network/HTTPRequestHeader.swift
  Marsiple/Common/Network/HTTPRequestMethod.swift
  Marsiple/Common/Network/MartianApi.swift
  Marsiple/Common/Network/PostsFetcher.swift
  Marsiple/Common/Persistence/.gitkeep
  Marsiple/Common/UI/.gitkeep
  Marsiple/Common/Utilities/.gitkeep
  Marsiple/Resources/Localization/Localizable.strings
  Marsiple/Resources/Other/Info.plist
Labels: aproved

#5 Code markers as warnings
  Marsiple.xcodeproj/project.pbxproj
Labels: aproved

#6 Post details - #1 View
  Marsiple.xcodeproj/project.pbxproj
  Marsiple/App/Post Details/PostDetailsTableViewCell.swift
  Marsiple/App/Post Details/PostDetailsView.swift
  Marsiple/App/Post Details/PostDetailsViewController.swift
  Marsiple/App/Posts/PostTableViewCell.swift
  Marsiple/App/Posts/PostsView.swift
  Marsiple/App/Posts/PostsViewController.swift
  Marsiple/Common/Localization/LocalizationKey.swift
  Marsiple/Common/Models/Comment.swift
  Marsiple/Common/UI/CellReuseIdentifier.swift
  Marsiple/Common/UI/TitleAndBodyView.swift
  Marsiple/Resources/Localization/Localizable.strings
Labels: approved

#7 Post details - #2 Fetching data
  Marsiple.xcodeproj/project.pbxproj
  Marsiple/App/Post Details/PostDetailsView.swift
  Marsiple/App/Post Details/PostDetailsViewController.swift
  Marsiple/App/Posts/PostsViewController.swift
  Marsiple/Common/Models/Comment.swift
  Marsiple/Common/Network/DataFetcher.swift
  Marsiple/Common/Network/DataFetcherError.swift
  Marsiple/Common/Network/MartianApi.swift
  Marsiple/Common/Network/PostsFetcher.swift
Labels: approved

#8 Comment - #1 View
  Marsiple.xcodeproj/project.pbxproj
  Marsiple/App/Post Details/PostDetailsViewController.swift
  Marsiple/Comment/CommentView.swift
  Marsiple/Comment/CommentViewController.swift
  Marsiple/Common/Extensions/UIBarButtonItem-Marsiple.swift
  Marsiple/Common/Localization/LocalizationKey.swift
  Marsiple/Resources/Localization/Localizable.strings
Labels: 1. approved

#11 Post details - main
  Marsiple.xcodeproj/project.pbxproj
  Marsiple/App/Post Details/PostDetailsTableViewCell.swift
  Marsiple/App/Post Details/PostDetailsView.swift
  Marsiple/App/Post Details/PostDetailsViewController.swift
  Marsiple/App/Posts/PostTableViewCell.swift
  Marsiple/App/Posts/PostsView.swift
  Marsiple/App/Posts/PostsViewController.swift
  Marsiple/Common/Localization/LocalizationKey.swift
  Marsiple/Common/Models/Comment.swift
  Marsiple/Common/Network/DataFetcher.swift
  Marsiple/Common/Network/DataFetcherError.swift
  Marsiple/Common/Network/MartianApi.swift
  Marsiple/Common/Network/PostsFetcher.swift
  Marsiple/Common/UI/CellReuseIdentifier.swift
  Marsiple/Common/UI/TitleAndBodyView.swift
  Marsiple/Resources/Localization/Localizable.strings
Labels: 1. approved
